name: CI (push & PR)

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
    paths:
      # Run CI only when these files/directories change
      - 'cmp-videoplayer/**'
      - 'sample/**'
      - 'gradle/**'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - 'build.gradle.kts'
      - '.github/workflows/ci.yml'
      - '.github/workflows/push-ci.yml'
      - 'maestro-e2e/**'
  pull_request:
    paths:
      # Same path filters for PRs
      - 'cmp-videoplayer/**'
      - 'sample/**'
      - 'gradle/**'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - 'build.gradle.kts'
      - '.github/workflows/ci.yml'
      - '.github/workflows/push-ci.yml'
      - 'maestro-e2e/**'

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Reuse CI (lint, build+tests, android UI)
    uses: ./.github/workflows/ci.yml
